apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/TonIveSat/intro-argo-cd'
    path: portal
    targetRevision: HEAD
  destination:
    namespace: portal
    name: eks
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
